CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_LED_STRIP=y
CONFIG_PULSE_IO=y
CONFIG_WS2812_STRIP_PULSE_IO=y
CONFIG_PULSE_IO_ESP32_RMT=y
